version: "3.8"
services:
  postgres:
    container_name: base_postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=neil
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mibaseneil
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php-server
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./html:/var/www/html
volumes:
  html: {}
  db: {}