version: "3.8"
services:
  postgres:
    container_name: base_postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=neil
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mibaseneil
      - POSTGRES_HOST=localhost
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php-server
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./html:/var/www/html
  codeigniter:
    build:
      context: ./
      dockerfile: Dockerfile
    image: php:7.3-apache
    container_name: php-codeigniter
    restart: always
    ports:
      - 3000:80
    volumes:
      - ./html2:/var/www/html
  python:
    build:
      context: ./
      dockerfile: Dockerfile-py
    container_name: python-server
    restart: always
    ports:
      - 5000:5000
    volumes: 
      - ./webpython:/webpython
    command: python manage.py runserver 0.0.0.0:5000
volumes:
  html: {}
  db: {}
  html2: {}
  web: {}